name       : python-docstring-to-markdown
version    : 0.10
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/d/docstring-to-markdown/docstring-to-markdown-0.10.tar.gz : 12f75b0c7b7572defea2d9e24b57ef7ac38c3e26e91c0e5547cfc02b1c168bf6
homepage   : https://github.com/python-lsp/docstring-to-markdown
license    : LGPL-2.1-or-later
component  : programming.python
summary    : On the fly conversion of Python docstrings to markdown
description: |
    On the fly conversion of Python docstrings to markdown. Currently can recognise reStructuredText and convert multiple of its features to Markdown. In the future will be able to convert Google docstrings too.
builddeps  :
    - python-build
    - python-installer
build      : |
    %python3_setup
install    : |
    %python3_install
