name       : python-docstring-to-markdown
version    : '0.12'
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/d/docstring-to-markdown/docstring-to-markdown-0.12.tar.gz : 40004224b412bd6f64c0f3b85bb357a41341afd66c4b4896709efa56827fb2bb
homepage   : https://github.com/python-lsp/docstring-to-markdown
license    : LGPL-2.1-or-later
component  : programming.python
summary    : On the fly conversion of Python docstrings to markdown
description: |
    On the fly conversion of Python docstrings to markdown. Currently can recognise reStructuredText and convert multiple of its features to Markdown. In the future will be able to convert Google docstrings too.
builddeps  :
    - python-build
    - python-installer
build      : |
    %python3_setup
install    : |
    %python3_install
